# Generated by Django 5.1.6 on 2025-04-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sale_price',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur')], max_length=45, unique=True),
        ),
    ]
